/**
 * Generates supabase/seed.sql from the TypeScript demo seed so that the local
 * demo store and a Supabase project contain identical data and identifiers.
 *
 *   npm run db:seed-sql
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { AMENITIES } from "../src/lib/constants";
import { SEED_AGENTS, buildSeedProperties } from "../src/lib/data/seed";

const OUT = join(import.meta.dirname, "..", "supabase", "seed.sql");

export function sqlString(value: string | null | undefined): string {
  if (value == null) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlArray(values: string[]): string {
  return `array[${values.map(sqlString).join(", ")}]::text[]`;
}

export function buildSeedSql(): string {
  const properties = buildSeedProperties();
  const lines: string[] = [
    "-- ════════════════════════════════════════════════════════════════════════════",
    "-- EstateX demo seed data — generated by scripts/generate-seed-sql.ts.",
    "-- Illustrative portfolio content only: not live listings or market data.",
    "-- Safe to re-run: existing seed rows are replaced.",
    "-- ════════════════════════════════════════════════════════════════════════════",
    "",
    "begin;",
    "",
    "insert into public.amenities (slug, label, icon) values",
    AMENITIES.map((a) => `  (${sqlString(a.slug)}, ${sqlString(a.label)}, ${sqlString(a.icon)})`).join(",\n") +
      "\non conflict (slug) do update set label = excluded.label, icon = excluded.icon;",
    "",
    "insert into public.agents (id, name, title, bio, languages) values",
    SEED_AGENTS.map(
      (a) =>
        `  (${sqlString(a.id)}, ${sqlString(a.name)}, ${sqlString(a.title)}, ${sqlString(a.bio)}, ${sqlArray(a.languages)})`,
    ).join(",\n") +
      "\non conflict (id) do update set name = excluded.name, title = excluded.title, bio = excluded.bio, languages = excluded.languages;",
    "",
    `delete from public.properties where id in (${properties.map((p) => sqlString(p.id)).join(", ")});`,
    "",
    "insert into public.properties (id, slug, name, tagline, description, city, locality, address, latitude, longitude, price, type, bedrooms, bathrooms, area_sqft, year_built, parking, status, featured, nearby, agent_id, created_at, updated_at) values",
    properties
      .map(
        (p) =>
          `  (${[
            sqlString(p.id),
            sqlString(p.slug),
            sqlString(p.name),
            sqlString(p.tagline),
            sqlString(p.description),
            sqlString(p.city),
            sqlString(p.locality),
            sqlString(p.address),
            p.latitude,
            p.longitude,
            p.price,
            `${sqlString(p.type)}::public.property_type`,
            p.bedrooms,
            p.bathrooms,
            p.areaSqft,
            p.yearBuilt ?? "null",
            p.parking,
            `${sqlString(p.status)}::public.property_status`,
            p.featured,
            `${sqlString(JSON.stringify(p.nearby))}::jsonb`,
            sqlString(p.agentId),
            sqlString(p.createdAt),
            sqlString(p.updatedAt),
          ].join(", ")})`,
      )
      .join(",\n") + ";",
    "",
    "insert into public.property_images (id, property_id, url, alt, kind, label, position, blur_data_url) values",
    properties
      .flatMap((p) => [
        ...p.images.map(
          (img) =>
            `  (${sqlString(img.id)}, ${sqlString(p.id)}, ${sqlString(img.url)}, ${sqlString(img.alt)}, 'photo', null, ${img.position}, ${sqlString(img.blurDataUrl ?? null)})`,
        ),
        ...p.floorPlans.map(
          (plan) =>
            `  (${sqlString(plan.id)}, ${sqlString(p.id)}, ${sqlString(plan.url)}, ${sqlString(`${plan.label} floor plan of ${p.name}`)}, 'floor_plan', ${sqlString(plan.label)}, ${plan.position}, null)`,
        ),
      ])
      .join(",\n") + ";",
    "",
    "insert into public.property_amenities (property_id, amenity_slug) values",
    properties
      .flatMap((p) => p.amenities.map((a) => `  (${sqlString(p.id)}, ${sqlString(a)})`))
      .join(",\n") + ";",
    "",
    "commit;",
    "",
  ];
  return lines.join("\n");
}

if (process.argv[1] && import.meta.filename === process.argv[1]) {
  writeFileSync(OUT, buildSeedSql());
  console.log(`Wrote ${OUT}`);
}
